package com.fedorov.wallmart.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CategoryModel {
    @ApiModelProperty(notes = "The category ID, generated by DB")
    private Long id;
    @ApiModelProperty(notes = "The category name")
    private String name;
}