package com.fedorov.wallmart.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProducerModel {
    @ApiModelProperty(notes = "The producer ID, generated by DB")
    private Long id;
    @ApiModelProperty(notes = "The producer name")
    private String name;
}