package com.fedorov.wallmart.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductModel {
    @ApiModelProperty(value = "autogenerated id")
    private Long id;
    @ApiModelProperty(notes = "this is a name of the product")
    private String name;
    @ApiModelProperty(notes = "this is a description of the product")
    private String description;
    @ApiModelProperty(notes = "this is a category id of the product")
    private Long categoryId;
    @ApiModelProperty(notes = "producer id of the product")
    private Long producerId;
    @ApiModelProperty(notes = "price of the product")
    private BigDecimal price;
}
